### ISSUE TITLE
Authentication returns an error when certain LDAP groups contain a '#' or other characters that are escaped in DNs

### ISSUE THREAD

**Issue by danefalvo** [OctopusDeploy/LdapAuthenticationProvider#49]
### What Happened
With the LDAP Authentication extension, if a Group that the user is in, is a Child or Grandchild of group with a name attrubute that contains a special Character. (i.e. '#') you will be presented with an LDAP error. 

This has also been raised as an OctopusServer issue here: https://github.com/OctopusDeploy/Issues/issues/7143

### **Reproduction**

**In the LDAP configuration**
Create a User "testUser" and place them in a LDAP group called "Group B". 
Make "Group B" a member of  "# Group A"

**In the Octopus instance:**
Configure an Octopus instance with LDAP. 
Set the LDAP "Nested Group Search Depth" to 2 or greater.

Create a Team and bind it to the LDAP group "Group B"
Apply some User Role Permissions.

Log into Octopus as testUser.

testUser should log in fine, but permission will not be applied.
The System Logs should return the Error Log.

### Error and Stacktrace

```
  2021-09-20 17:23:20.6990      1    145 ERROR  LDAP search for <username> failed.
  LdapLocalException: Invalid value in escape sequence "#" (87) Filter Error
```

### Workaround
Disabling nested group support by setting `Nested Group Depth` to `0` will avoid the problematic queries.  This does have the side effect that user membership in Octopus will only be attributed from groups they are direct members in rather than parent/grandparent/etc groups of those they are members in.

Alternatively if the problematic group names in the LDAP directory can be renamed to not include the [special characters](https://ldapwiki.com/wiki/DN%20Escape%20Values) that are escaped in LDAP distinguished names, that will also stop the issue occuring.

### More Information
**Internal Ticket:** https://octopus.zendesk.com/agent/tickets/76076

**Comment by ryangribble** [comment]
The issue is, the user group membership search query is returning the group DNs with escaped characters, eg for a group named `Child # Group` the Ldap library returns `CN=Child \# Group,OU=Groups,DC=corp,DC=contoso,DC=com` 

[List of characters](https://ldapwiki.com/wiki/DN%20Escape%20Values) that are escaped in DNs (distinguished names)

But when this DN is fed back into the NestedGroup parent search filter `(&(objectClass=group)(member=CN=Child \# Group,OU=Groups,DC=corp,DC=contoso,DC=com))` the Ldap library is bombing due to the escapin being present.  It is blowing up in `UnescapeString()` which clearly isnt doing a very good job of unescaping these 🤣 

The "fix" is to use non escaped value `(&(objectClass=group)(member=CN=Child # Group,OU=Groups,DC=corp,DC=contoso,DC=com))` and this then returns results as expected.

We need to look into whether this should be ultimately fixed upstream (why is it failing in an Unesccape function...)or if we are holding it wrong (do we need to unescape ourselves before calling it?).  My understanding was it is meant to handle all of the escaping/unescaping internally and the stack trace sounds like it's trying to do that.

```
   at Novell.Directory.Ldap.Rfc2251.RfcFilter.UnescapeString(String stringRenamed)
   at Novell.Directory.Ldap.Rfc2251.RfcFilter.ParseFilterComp()
   at Novell.Directory.Ldap.Rfc2251.RfcFilter.ParseFilterList()
   at Novell.Directory.Ldap.Rfc2251.RfcFilter.ParseFilterComp()
   at Novell.Directory.Ldap.Rfc2251.RfcFilter.ParseFilter()
   at Novell.Directory.Ldap.Rfc2251.RfcFilter..ctor(String filter)
   at Novell.Directory.Ldap.LdapSearchRequest..ctor(String baseRenamed, Int32 scope, String filter, String[] attrs, Int32 dereference, Int32 maxResults, Int32 serverTimeLimit, Boolean typesOnly, LdapControl[] cont)
   at Novell.Directory.Ldap.LdapConnection.Search(String base, Int32 scope, String filter, String[] attrs, Boolean typesOnly, LdapSearchQueue queue, LdapSearchConstraints cons)
   at Novell.Directory.Ldap.LdapConnection.Search(String base, Int32 scope, String filter, String[] attrs, Boolean typesOnly, LdapSearchConstraints cons)
   at Novell.Directory.Ldap.LdapConnection.Search(String base, Int32 scope, String filter, String[] attrs, Boolean typesOnly)
   at Ldap.Integration.Tests.IExternalGroupRetrieverTests.TheReadMethod.TestFilters() in D:\repos\LdapAuthenticationProvider\source\Ldap.Integration.Tests\IExternalGroupRetrieverTests.cs:line 24
```

**Comment by ryangribble** [comment]
Query raised on upstream repo but we will likely need to unescape these oursleves for now:
https://github.com/dsbenghe/Novell.Directory.Ldap.NETStandard/issues/175

I also confirmed with a few of the other characters such as `,` `(` that the same issue occurs
